spring:
  application:
    name: monew-server

  profiles:
    active: dev

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, prometheus

  endpoint:
    health:
      show-details: always
