spring:
  application:
    name: monew-batch

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: dev

  batch:
    job:
      enabled: false

logging:
  level:
    root: info
    com.monew: info

backup:
  enabled: ${BACKUP_ENABLED:true}
#  cron: ${ARTICLE_BACKUP_CRON:0 30 3 * * *}
  cron: ${ARTICLE_BACKUP_CRON:0 50 18 * * *}
  storage:
    type: ${BACKUP_STORAGE_TYPE:local}
    local:
      root-path: ${BACKUP_LOCAL_ROOT_PATH:.monew/backups}
    s3:
      bucket: ${BACKUP_S3_BUCKET:}
      prefix: ${BACKUP_S3_PREFIX:backups/articles}
      region: ${AWS_REGION:ap-northeast-2}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers

  endpoint:
    health:
      show-details: always

monew:
  api:
    naver:
      base-url: ${NAVER_BASE_URL:https://openapi.naver.com}
      client-id: ${NAVER_CLIENT_ID:}
      client-secret: ${NAVER_CLIENT_SECRET:}

  article-collect:
    cron: ${ARTICLE_COLLECT_CRON:0 0 * * * *}
    naver-display: ${ARTICLE_COLLECT_NAVER_DISPLAY:100}
    rss-limit: ${ARTICLE_COLLECT_RSS_LIMIT:100}
    retry-max-attempts: ${ARTICLE_COLLECT_RETRY_MAX_ATTEMPTS:4}
    retry-initial-delay-millis: ${ARTICLE_COLLECT_RETRY_INITIAL_DELAY_MILLIS:1000}
    retry-max-delay-millis: ${ARTICLE_COLLECT_RETRY_MAX_DELAY_MILLIS:2000}

  rss:
    hankyung:
      url: ${HANKYUNG_RSS_URL:https://www.hankyung.com/feed/all-news}
    chosun:
      url: ${CHOSUN_RSS_URL:https://www.chosun.com/arc/outboundfeeds/rss/?outputType=xml}
    yeonhap:
      urls:
        - ${YEONHAP_RSS_POLITICS_URL:http://www.yonhapnewstv.co.kr/category/news/politics/feed/}
        - ${YEONHAP_RSS_ECONOMY_URL:http://www.yonhapnewstv.co.kr/category/news/economy/feed/}
        - ${YEONHAP_RSS_SOCIETY_URL:http://www.yonhapnewstv.co.kr/category/news/society/feed/}
        - ${YEONHAP_RSS_LOCAL_URL:http://www.yonhapnewstv.co.kr/category/news/local/feed/}
        - ${YEONHAP_RSS_INTERNATIONAL_URL:http://www.yonhapnewstv.co.kr/category/news/international/feed/}
        - ${YEONHAP_RSS_CULTURE_URL:http://www.yonhapnewstv.co.kr/category/news/culture/feed/}
        - ${YEONHAP_RSS_SPORTS_URL:http://www.yonhapnewstv.co.kr/category/news/sports/feed/}
        - ${YEONHAP_RSS_WEATHER_URL:http://www.yonhapnewstv.co.kr/category/news/weather/feed/}
